# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe03797c788b64da33af48b93fda87e3ddba10835961493dd86277e781b3fc6cbadc251389a9d6e542c6c525c2d62fafebc8709fc6eb88b934e43fe98b0b0f47

test:
  secret_key_base: 566986c577f77a0dc67c45179de5e06b7ffc14fea2957e4f31be5e02b5544f8d3c2e7b472f315f12d4f70a2e82513cf66ef410e02954afeced57fbe8b9b2a9ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
